name: Conduit CI Pipeline

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test with coverage
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage" --results-directory ./TestResults
      
    - name: Generate test report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: xUnit Tests
        path: '**/TestResults/*.trx'
        reporter: dotnet-trx
        fail-on-error: false
        
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        directory: ./TestResults
        fail_ci_if_error: false
        verbose: true
        
    - name: Upload test results as artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: ./TestResults
        retention-days: 30
      
  benchmarks:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Run Benchmarks
      run: dotnet run --project tests/Conduit.Benchmark/Conduit.Benchmark.csproj -c Release
      
    - name: Upload benchmark results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: benchmark-results
        path: BenchmarkDotNet.Artifacts
        retention-days: 30